// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  insertone() — basic sorted insertion
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: insert 22 into sorted [12,15,19,21,25,...,43] keeps sort", "[T1]")
{
    int n[100] = {12, 15, 19, 21, 25, 27, 29, 33, 37, 43};
    int len = 10;
    insertone(n, len, 22);
    REQUIRE(len == 11);
    int exp[] = {12, 15, 19, 21, 22, 25, 27, 29, 33, 37, 43};
    for (int i = 0; i < 11; i++) REQUIRE(n[i] == exp[i]);
}

TEST_CASE("T1b: insert 5 at the beginning of [12,15,19,21]", "[T1]")
{
    int n[100] = {12, 15, 19, 21};
    int len = 4;
    insertone(n, len, 5);
    REQUIRE(len == 5);
    int exp[] = {5, 12, 15, 19, 21};
    for (int i = 0; i < 5; i++) REQUIRE(n[i] == exp[i]);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  deleteone() — remove a matching value, length decreases
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: delete 19 from [12,15,19,21,25,27,29,33,37,43]", "[T2]")
{
    int n[100] = {12, 15, 19, 21, 25, 27, 29, 33, 37, 43};
    int len = 10;
    deleteone(n, len, 19);
    REQUIRE(len == 9);
    int exp[] = {12, 15, 21, 25, 27, 29, 33, 37, 43};
    for (int i = 0; i < 9; i++) REQUIRE(n[i] == exp[i]);
}

TEST_CASE("T2b: delete first element 12 leaves rest intact", "[T2]")
{
    int n[100] = {12, 15, 19, 21, 25};
    int len = 5;
    deleteone(n, len, 12);
    REQUIRE(len == 4);
    int exp[] = {15, 19, 21, 25};
    for (int i = 0; i < 4; i++) REQUIRE(n[i] == exp[i]);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  insertone() — edge cases: largest, smallest, single-element start
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: insert 99 (largest) appends to end of [10,20,30]", "[T3]")
{
    int n[100] = {10, 20, 30};
    int len = 3;
    insertone(n, len, 99);
    REQUIRE(len == 4);
    int exp[] = {10, 20, 30, 99};
    for (int i = 0; i < 4; i++) REQUIRE(n[i] == exp[i]);
}

TEST_CASE("T3b: insert into single-element array preserves order", "[T3]")
{
    int n[100] = {50};
    int len = 1;
    insertone(n, len, 30);
    REQUIRE(len == 2);
    REQUIRE(n[0] == 30);
    REQUIRE(n[1] == 50);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  Integration — insert then delete restores invariant
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: insert 50 then delete 50 returns original array + length", "[T4]")
{
    int n[100] = {10, 20, 30, 40, 60, 70};
    int len = 6;
    insertone(n, len, 50);
    REQUIRE(len == 7);
    deleteone(n, len, 50);
    REQUIRE(len == 6);
    int exp[] = {10, 20, 30, 40, 60, 70};
    for (int i = 0; i < 6; i++) REQUIRE(n[i] == exp[i]);
}

TEST_CASE("T4b: delete then insert at same value restores array (different position OK)", "[T4]")
{
    int n[100] = {5, 10, 15, 20, 25};
    int len = 5;
    deleteone(n, len, 15);
    REQUIRE(len == 4);
    insertone(n, len, 15);
    REQUIRE(len == 5);
    int exp[] = {5, 10, 15, 20, 25};
    for (int i = 0; i < 5; i++) REQUIRE(n[i] == exp[i]);
}
